# Generated by Django 3.0.3 on 2020-03-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ImageField(upload_to='')),
                ('book_name', models.CharField(max_length=250)),
                ('book_blurb', models.CharField(max_length=1000)),
            ],
        ),
    ]
