# Generated by Django 3.0.3 on 2020-03-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookversations', '0003_auto_20200307_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='book_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
