# Generated by Django 3.0.3 on 2020-03-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookversations', '0005_auto_20200307_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
