# Generated by Django 3.0.3 on 2020-03-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookversations', '0006_auto_20200308_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='book_blurb',
            field=models.TextField(),
        ),
    ]
